### ISSUE TITLE
Error when running Powershell script

### ISSUE THREAD

**Issue by DiaBomb** [borogk/zdoom-cameraman#1]
First, apparently the default setting, at least on my install of Windows 10, is set to block any untrusted scripts. Probably something that should be put in the installations instructions. [A page explaining it](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.1)

After all that, when I try to run the .ps1 script, the following error comes out (file paths partially hidden):
```
Start-Process : This command cannot be run completely because the system cannot find all the information required.
At C:\Users\DiaBomb\Desktop\...\GZDoom\editor.ps1:31 char:11
+ $gzdoom = Start-Process -FilePath $GzdoomPath -ArgumentList $allArgs  ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

Wait-Process : Cannot validate argument on parameter 'Id'. The argument is null or empty. Provide an argument that is
not null or empty, and then try the command again.
At C:\Users\DiaBomb\Desktop\Doom\GZDoom\editor.ps1:32 char:18
+ Wait-Process -Id $gzdoom.Id
+                  ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Wait-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WaitProcessCommand

Get-Content : Cannot find path 'C:\Users\DiaBomb\Desktop\Doom\GZDoom\editor.log' because it does not exist.
At C:\Users\DiaBomb\Desktop\Doom\GZDoom\editor.ps1:35 char:19
+ foreach ($line in Get-Content $editorLogPath)
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\...Doom\editor.log:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Remove-Item : Cannot find path 'C:\Users\...\Desktop\Doom\GZDoom\editor.log' because it does not exist.
At C:\Users\...\Desktop\Doom\GZDoom\editor.ps1:68 char:1
+ Remove-Item $editorLogPath -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\...Doom\editor.log:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

```

**Comment by DiaBomb** [comment]
It's a problem on my side. This error appears if you point to the gzdoom folder in the settings file and not the exe. It wasn't exactly obvious in the installation instructions if it needs just the folder or the exe.

Should I close this now?

**Comment by borogk** [comment]
> First, apparently the default setting, at least on my install of Windows 10, is set to block any untrusted scripts. Probably something that should be put in the installations instructions. 

This was already taken care of a few days ago, see ["Troubleshooting" section](https://github.com/borogk/zdoom-cameraman/blob/main/docs/ch01.installation.md#troubleshooting) in the installation manual.

> This error appears if you point to the gzdoom folder in the settings file and not the exe. It wasn't exactly obvious in the installation instructions if it needs just the folder or the exe.

You are not the first person to make that mistake, I'll clarify this in the docs and then close the issue.

Thanks for the feedback @DiaBomb !
